# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "squeese"
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter van Hardenberg"]
  s.date = "2013-05-11"
  s.description = "A job queueing and background workers system using SQS.  Inspired by the Stalker gem."
  s.email = "pvh@heroku.com"
  s.executables = ["squeese"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/squeese",
    "lib/squeese.rb"
  ]
  s.homepage = "http://github.com/pvh/squeese"
  s.require_paths = ["lib"]
  s.rubyforge_project = "squeese"
  s.rubygems_version = "1.8.24"
  s.summary = "A job queueing and background workers system using SQS."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<activesupport>, ["~> 3.1.12"])
      s.add_development_dependency(%q<aws>, [">= 0"])
      s.add_development_dependency(%q<json_pure>, [">= 0"])
      s.add_runtime_dependency(%q<aws>, [">= 0"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<activesupport>, ["~> 3.1.12"])
      s.add_dependency(%q<aws>, [">= 0"])
      s.add_dependency(%q<json_pure>, [">= 0"])
      s.add_dependency(%q<aws>, [">= 0"])
      s.add_dependency(%q<json_pure>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.3.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<activesupport>, ["~> 3.1.12"])
    s.add_dependency(%q<aws>, [">= 0"])
    s.add_dependency(%q<json_pure>, [">= 0"])
    s.add_dependency(%q<aws>, [">= 0"])
    s.add_dependency(%q<json_pure>, [">= 0"])
  end
end

